version: "3.8"
services:
  backend-flask:
    environment:
      FRONTEND_URL: "http://localhost:3000"
      BACKEND_URL: "http://localhost:4567"
      OTEL_SERVICE_NAME: "${HONEYCOMB_SERVICE_NAME}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io"
      OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${HONEYCOMB_API_KEY}"
      FLASK_DEBUG: 1

      # For Flask-AWSCognito
      AWS_DEFAULT_REGION: "ca-central-1"
      AWS_COGNITO_USER_POOL_ID: "ca-central-1_jhq6897GB"
      AWS_COGNITO_USER_POOL_CLIENT_ID: "2stl3jgj1acamjt2sfnum0t4p6"
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:4567"

      # For aws-amplify
      REACT_APP_AWS_PROJECT_REGION: "ca-central-1"
      REACT_APP_AWS_COGNITO_REGION: "ca-central-1"
      REACT_APP_AWS_USER_POOLS_ID: "ca-central-1_jhq6897GB"
      REACT_APP_AWS_CLIENT_ID: "2stl3jgj1acamjt2sfnum0t4p6"
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
  dynamodb-local:
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

# the name flag is a hack to change the default prepend folder
# name when outputting the image names
networks:
  internal-network:
    driver: bridge
    name: cruddur

volumes:
  db:
    driver: local